In [7]:
import pickle
import numpy as np
import os

In [2]:
keypoint_path = '../data/wlasl_2000/keypoints_hrnet_dark_coco_wholebody.pkl'
hands_path = 'output_files'

In [3]:
with open(keypoint_path, 'rb') as f:
    keypoints = pickle.load(f)

In [ ]:
hand_keypoints_range = list(range(91, 133))

In [20]:
for key in keypoints.keys():
    print(keypoints[key].shape)
    hand_array = np.load(os.path.join(hands_path,key+'.npy'))*256
    print(hand_array.shape)
    
    keypoints[key][:,91:133,:] = hand_array

(60, 133, 3)
(60, 42, 3)
(121, 133, 3)
(121, 42, 3)
(52, 133, 3)
(52, 42, 3)
(30, 133, 3)
(30, 42, 3)
(36, 133, 3)
(36, 42, 3)
(25, 133, 3)
(25, 42, 3)
(51, 133, 3)
(51, 42, 3)
(66, 133, 3)
(66, 42, 3)
(83, 133, 3)
(83, 42, 3)
(97, 133, 3)
(97, 42, 3)
(56, 133, 3)
(56, 42, 3)
(87, 133, 3)
(87, 42, 3)
(26, 133, 3)
(26, 42, 3)
(77, 133, 3)
(77, 42, 3)
(86, 133, 3)
(86, 42, 3)
(88, 133, 3)
(88, 42, 3)
(31, 133, 3)
(31, 42, 3)
(31, 133, 3)
(31, 42, 3)
(36, 133, 3)
(36, 42, 3)
(27, 133, 3)
(27, 42, 3)
(40, 133, 3)
(40, 42, 3)
(23, 133, 3)
(23, 42, 3)
(41, 133, 3)
(41, 42, 3)
(14, 133, 3)
(14, 42, 3)
(46, 133, 3)
(46, 42, 3)
(53, 133, 3)
(53, 42, 3)
(66, 133, 3)
(66, 42, 3)
(57, 133, 3)
(57, 42, 3)
(84, 133, 3)
(84, 42, 3)
(76, 133, 3)
(76, 42, 3)
(75, 133, 3)
(75, 42, 3)
(64, 133, 3)
(64, 42, 3)
(85, 133, 3)
(85, 42, 3)
(34, 133, 3)
(34, 42, 3)
(42, 133, 3)
(42, 42, 3)
(25, 133, 3)
(25, 42, 3)
(58, 133, 3)
(58, 42, 3)
(86, 133, 3)
(86, 42, 3)
(46, 133, 3)
(46, 42, 3)
(64, 133, 3)
(64, 42, 3

In [21]:
with open('keypoints_hrnet_dark_coco_wholebody_mediapipe_hand.pkl', 'wb') as handle:
    pickle.dump(keypoints, handle, protocol=pickle.HIGHEST_PROTOCOL)


In [19]:
for i in range(keypoints[key].shape[0]):
    for j in range(keypoints[key].shape[1]):
        print(keypoints[key][i][j])

[124.56    75.56     0.9526]
[132.8    67.6     0.968]
[116.      67.1      0.9644]
[143.2     74.5      0.9404]
[105.     74.      0.935]
[168.5   122.1     0.836]
[ 81.25  125.56    0.841]
[184.9   192.4     0.703]
[ 69.7   198.8     0.701]
[190.1    234.1      0.4316]
[ 73.4    233.9      0.4011]
[155.2    221.1      0.7036]
[ 98.6   224.8     0.633]
[133.      82.9      0.5205]
[113.44   82.1     0.542]
[125.25   64.9     0.521]
[124.4     64.6      0.5103]
[142.6    74.8     0.646]
[142.6     74.6      0.6216]
[118.1   61.84   0.49]
[106.2     73.7      0.6665]
[106.25   73.44    0.657]
[116.9     62.22     0.4917]
[105.9     69.75     0.9287]
[105.94   74.3     0.965]
[106.5    78.8     0.981]
[107.44    83.44     0.9736]
[108.9    88.      0.975]
[111.44    92.06     0.9697]
[114.9    95.44    0.994]
[119.1    97.6     0.979]
[123.9    98.5     0.988]
[128.5    98.      0.978]
[132.9     96.       0.9805]
[136.4    92.75    0.981]
[139.      88.75     0.9844]
[140.6     84.1    

In [18]:
keypoints[key].shape[0]

58